users:
    authelia:
        # default password is authelia
        password: "$6$rounds=50000$BpLnfgDsc2WD8F2q$Zis.ixdg9s/UOJYrs56b5QEZFiZECu0qZVNsIYxBaNJ7ucIL.nlxVCT5tqh8KHG8X4tlwCFm5r6NTOZZ5qRFN/"
        displayname: Authelia User
        email: authelia_user@mail.example.com
        groups:
            - admins
            - dev
        disabled: false
